name: Build (Maven)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Intenta Temurin 24
      - name: Setup Java 24 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '24'
          cache: maven

      # Si por alguna razón runner no encuentra Temurin 24,
      # descomentar este bloque y comenta el de arriba para usar Zulu 24.
      # - name: Setup Java 24 (Zulu)
      #   uses: actions/setup-java@v4
      #   with:
      #     distribution: zulu
      #     java-version: '24'
      #     cache: maven

      - name: Build with Maven
        run: mvn -B -DskipTests package

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Files-to-PDF
          path: |
            target/*.jar
