name: Build (Maven)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      # ⬇️ Si tu pom.xml está en una subcarpeta, descomenta esto y ajusta la ruta:
      # - name: Build with Maven (subcarpeta)
      #   run: mvn -B -DskipTests package
      #   working-directory: ./Programa_PDF

      - name: Build with Maven
        run: mvn -B -DskipTests package

      - name: Upload JAR artifact
      # Sube el jar generado en target/
        uses: actions/upload-artifact@v4
        with:
          name: Files-to-PDF-artifacts
          path: |
            target/*.jar
            target/*.zip
            target/*.exe
